name: PMMP-AI
main: Renz\AIAssistant\Main
version: 1.0.0
api: 5.20.0
author: Renz
description: Advanced AI Assistant for Minecraft server...
website: https://github.com/RenzMc/PMMP-AI

softdepend:
  - EconomyAPI
  - BedrockEconomy
  - CoinAPI

permissions:
  pmmp-ai.command.ai:
    description: "Allows the user to use the AI Assistant"
    default: true
  pmmp-ai.admin:
    description: "Allows the user to access admin settings for the AI Assistant"
    default: op